In [1]:
# pytorch自动求导实现
import torch

In [2]:
x = torch.arange(4, dtype=torch.float64, device='cuda')
x.requires_grad  = True
print(x)
print(x.grad)

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float64,
       requires_grad=True)
None


In [3]:
y = torch.dot(x, x) * 2 # y = 2x^2
print(y)

tensor(28., device='cuda:0', dtype=torch.float64, grad_fn=<MulBackward0>)


In [4]:
print(x.grad)
y.backward(retain_graph=True) # 让pytorch让你帮忙计算导数
x.grad

None


tensor([ 0.,  4.,  8., 12.], device='cuda:0', dtype=torch.float64)

In [5]:
x.grad == 4 * x # 符合我们的求导公式

tensor([True, True, True, True], device='cuda:0')

In [6]:
# 默认情况下，pytorch会默认把梯度累加，在计算之前我们要清零梯度
x.grad.zero_()
y = x.sum()
y.backward(retain_graph=True)
x.grad

tensor([1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)

In [19]:
x.grad.zero_()
y = torch.dot(x*x, torch.ones(x.shape[0],device='cuda', dtype=torch.float64))
# 上面与y=sum().backward()等价
y.backward()
print(x.grad)

tensor([0., 2., 4., 6.], device='cuda:0', dtype=torch.float64)


In [21]:
x.grad.zero_()
y = x * x
u = y.detach() # u变成了与x无关的常数
z = u * x # z对x的导数就变成了u

z.sum().backward()
x.grad

tensor([0., 1., 4., 9.], device='cuda:0', dtype=torch.float64)

ModuleNotFoundError: No module named 'cuda:0'