In [1]:
# pytorch自动求导实现
import torch

In [8]:
x = torch.arange(4, dtype=torch.float64, device='cuda')
x.requires_grad  = True
print(x)
print(x.grad)

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float64,
       requires_grad=True)
None


In [26]:
y = torch.dot(x, x) * 2 # y = 2x^2
print(y)

tensor(28., device='cuda:0', dtype=torch.float64, grad_fn=<MulBackward0>)


In [30]:
print(x.grad)
y.backward(retain_graph=True) # 让pytorch让你帮忙计算导数
x.grad

tensor([0., 0., 0., 0.], device='cuda:0', dtype=torch.float64)


tensor([ 0.,  4.,  8., 12.], device='cuda:0', dtype=torch.float64)

In [31]:
x.grad == 4 * x # 符合我们的求导公式

tensor([True, True, True, True], device='cuda:0')

In [32]:
# 默认情况下，pytorch会默认把梯度累加，在计算之前我们要清零梯度
x.grad.zero_()
y = x.sum()
y.backward(retain_graph=True)
x.grad

tensor([1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)