In [2]:
# 这是一些对数据的基本操作,对应视频04p2
import torch


In [5]:
# 新建一个torch的tensor
x = torch.arange(12)
print(x)
# 像numpy一样，能够reshape
x = x.reshape(3,4)
# 生成一堆0，并指定shape
zeros = torch.zeros((2,3,4))
print(zeros)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
import numpy as np

# torch兼容了numpy
a = np.zeros((2,3,4))
b = torch.tensor(a)
print(b)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=torch.float64)


In [8]:
# 普通的list也可以直接扔进去
a = [[1,2,3], [4,5,6]]
b = torch.tensor(a)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
# 像这种直接用运算符对两个tensor进行操作，一般遵循element-wise原则
a = torch.tensor([1, 2, 4, 8])
b = torch.tensor([2, 2, 2, 2])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([ 3,  4,  6, 10])
tensor([-1,  0,  2,  6])
tensor([ 2,  4,  8, 16])
tensor([0.5000, 1.0000, 2.0000, 4.0000])


In [14]:
# 如何把两个tensor整成一个tensor？
a = torch.arange(12).reshape(3,4)
b = torch.tensor([[2,3,4,5], [1,2,3,4], [3,4,5,6]])
print(a)
print(b)
print(torch.cat((a, b), dim=0)) # 垂直扩展
print(torch.cat((a, b), dim=1)) # 水平扩展


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[2, 3, 4, 5],
        [1, 2, 3, 4],
        [3, 4, 5, 6]])


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 6 but got size 4 for tensor number 1 in the list.

In [20]:
# torch也有广播机制
a = torch.arange(5)
b = torch.arange(25).reshape(5,5)

# 行列都不一样呢？
c = torch.arange(2).reshape(1,2)
d = torch.arange(4).reshape(4,1)
print(c)
print(d)
print(c+d)
# 把列向量扩展一下，弄成4x2的，再用行向量去加

tensor([[0, 1]])
tensor([[0],
        [1],
        [2],
        [3]])
tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])


In [24]:
# torch访问元素的方法和numpy很像
x = torch.arange(4)
x[1:3] = torch.tensor([5,6])
print(x)

tensor([0, 5, 6, 3])


In [29]:
# 如何进行tensor的原地操作？
x = torch.tensor([3,4,5,6,7])
print(id(x))
x = x + 1
print(id(x))

# 第一种
x += 1
print(id(x))
# 第二种
x[:] = x + 1
print(id(x))

140308572277952
140308572275712
140308572275712
140308572275712
